source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3', '1.3.5'

group :development do
	gem 'pg', '0.14.1'
end

group :production do
	gem 'pg', '0.14.1'
end

gem 'execjs'
gem 'therubyracer'

gem 'bcrypt-ruby', :require=>'bcrypt'
# Gema que permite encriptar los passwords

# Gema que permite la autenticación con las Redes Sociales.
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'

# Gema que permite crear los pdf
gem 'wkhtmltopdf-binary'
gem 'wicked_pdf'
gem 'meta_search'

gem "heroku"
gem 'prototype-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.2'
  gem 'coffee-script'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.2.3'
end

gem 'jquery-rails', '2.0.2'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
